version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: publicaciones_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: unah1234
      MYSQL_DATABASE: publicaciones_db
      MYSQL_USER: unah_admin
      MYSQL_PASSWORD: unah1234
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
